### ISSUE TITLE
[bug: Chapter03 -> issues.service.ts ->  updateIssue() ] - The current declaration it's assigning value instead comparing it

### ISSUE THREAD

**Issue by rodoherrera** [PacktPublishing/Angular-Projects-Second-Edition#1]
https://github.com/PacktPublishing/Angular-Projects-Second-Edition/blob/533854e8b1a2c1b7e1be26c02da7c2aa93f8ba02/Chapter03/src/app/issues.service.ts#L40

Here should be have three (or two) equals operators. **The current declaration it's assigning value instead comparing it**:

**- Current version:** 
   ` const existingIssue = this.issues.find(i => i.issueNo = issueNo);`

**- Bugfix version:**
  `const existingIssue = this.issues.find(i => i.issueNo === issueNo);`

**NOTE: Cheers, i'm enjoying your book!!**

**Comment by bampakoa** [comment]
Thank you @rodoherrera for spotting that 🙏. I have provided a fix in the `exercise` branch in case you want to check it out.

I am very happy that you enjoy the book and I hope the rest of the chapters will prove useful to your needs 😊
