### ISSUE TITLE
Chapter 5 (ngx-wig) setup error

### ISSUE THREAD

**Issue by mikemuin** [PacktPublishing/Angular-Projects-Second-Edition#2]
Hello, I am working on Chapter 5 (WYSIWYG Editor) and after installing ngx-wig, I have been getting these kinds of errors:

```
Error: ../../../../../node_modules/ngx-wig/lib/ngx-wig.module.d.ts:15:25 - error TS2694: Namespace '"/Users/xxx/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

15     static ɵinj: ɵngcc0.ɵɵInjectorDeclaration<NgxWigModule>;
```

I followed the book scripts exactly.

Here's my Angular Set-up:
```
Angular CLI: 12.1.4
Node: 14.17.4
Package Manager: npm 7.20.3
OS: darwin x64

Angular: 12.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5
```
All other previous scripts and new test project installs work with `ng-serve`. But this one doesn't work. I only get `Cannot GET /` on the page.

Hope you can help. Really looking forward to this chapter. Thanks!

**Comment by bampakoa** [comment]
Hey @mikemuin, I tried to reproduce your problem with no luck. Could you please try removing your `node_modules` folder and your `package-lock.json` file and then run `npm install` again? Also, I guess you have done that but could you please make sure that the dependencies of your `package.json` file regarding Angular and ngx-wig match those in the [GitHub repo](https://github.com/PacktPublishing/Angular-Projects-Second-Edition/blob/main/Chapter05/package.json)?

**Comment by mikemuin** [comment]
@bampakoa That worked! The changes/updates in the dependencies of `package.json` worked. That was the missing element in all my efforts. Thanks again!

**Comment by bampakoa** [comment]
@mikemuin I am glad you solved it 😊 Could you please state which dependencies you changed, in case others have the same problem?

**Comment by mikemuin** [comment]
Honestly, I'm not exactly sure which changes made the difference. :) It may also be the versions of the dependencies.

For the working instance, I started a new project via cli. Then copied-pasted the `package.json` you referenced in the solution. Then did `npm install`.

Here is the original `package.json` in the project that had errors.

```json
{
  "name": "my-editor",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.1.0",
    "@angular/common": "~12.1.0",
    "@angular/compiler": "~12.1.0",
    "@angular/core": "~12.1.0",
    "@angular/forms": "~12.1.0",
    "@angular/platform-browser": "~12.1.0",
    "@angular/platform-browser-dynamic": "~12.1.0",
    "@angular/router": "~12.1.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.4",
    "@angular/cli": "~12.1.4",
    "@angular/compiler-cli": "~12.1.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.3.2"
  }
}

```

**Comment by bampakoa** [comment]
Thanks for your feedback @mikemuin 🙏

**Comment by bampakoa** [comment]
Thanks for your feedback @mikemuin. Except for the `@types/node` package that it should be version `^15.6.0` according to the book chapter, everything else works well with the `ngx-wig` library. So, I cannot really tell what the problem was. In case it reappears or you have any other problem, please let me know 🙏
