### ISSUE TITLE
AngularFire API v. 7.0.0 (released 2021-08-25 for Angular 12) includes Breaking Changes for Chapter 6 Project

### ISSUE THREAD

**Issue by dchennells** [PacktPublishing/Angular-Projects-Second-Edition#3]
The path of least resistance is using the compatibility mode (@angular/fire/* changes to @angular/fire/compat/*).  Alternatively, at an appropriate juncture, code compatible with the new API could be implemented.  The angularfire doc linked below currently warns, "the new API isn't feature complete." 

See https://github.com/angular/angularfire/blob/master/docs/version-7-upgrade.md and https://stackoverflow.com/a/68939303.

**Comment by bampakoa** [comment]
Thanks a lot, @dchennells for pointing that out 🙏 I just pushed a patch in the GitHub repo that fixes the issue. Let me know if you have any problems upgrading to AngularFire 7.
