### ISSUE TITLE
Project 2 assets image path

### ISSUE THREAD

**Issue by Jriera** [PacktPublishing/Angular-Projects-Second-Edition#5]
In the contact component the image is referenced as `assets/angular.png` . This works when using ng serve but will break when serving the project with scully. 
The fix I found is to use a relative path (although it might not look as clean)

`<img class="card-img-top" src="../../assets/angular.png" alt="Angular Logo">`

**Comment by bampakoa** [comment]
Hey, @Jriera 👋 Thanks for the feedback 🙏

How do you serve the project with Scully? Which command do you use and then which URL do you use?

**Comment by Jriera** [comment]
I use `scully:serve` as instructed in the book. I haven't tried to deploy it but already in local environment when using `npm run scully:serve` the image does not display.
It does work when using `ng serve` though

**Comment by bampakoa** [comment]
Thanks for the clarification and for your kind words 😃 Could you please let me know which Angular and Scully version are you using because I could not reproduce it with Angular 12 and Scully 1.0

**Comment by Jriera** [comment]
I feel I owe you an apology. As I went to check my versions I tested once again the issue and it is now working perfectly with all the paths `/assets/angular.png`  `assets/angular.png` and the relative one I had originally. 
I am not sure why it didn't work previously. as I haven't updated anything in that workspace specifically so it might have been something on my end.
Again my apologies :(

**Comment by bampakoa** [comment]
No need to apologize @Jriera 😃 I am glad that it worked finally. If you need any further help with the rest of the chapters, please let me know. Happy holidays and wishing you a very happy and prosperous new year 🎆🎇
