### ISSUE TITLE
Project Chapter 3 : ng add @clr/angular fails Unable to find compatible package

### ISSUE THREAD

**Issue by mwhayford** [PacktPublishing/Angular-Projects-Second-Edition#6]
‼ Unable to find compatible package.  Using 'latest' tag.
‼ Package has unmet peer dependencies. Adding the package may not succeed.

The package @clr/angular@12.0.7 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: issue-trackker@0.0.0
npm ERR! Found: @angular/common@13.0.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from @clr/angular@12.0.7
npm ERR! node_modules/@clr/angular
npm ERR!   @clr/angular@"12.0.7" from the root project

How does one resolve this? I tried downgrading the @angular/common libraries but was unsuccessful in getting this to  install.

**Comment by bampakoa** [comment]
Hey @mwhayford 👋 Did you find a solution to your problem?
