### ISSUE TITLE
Not enough task and explanations about the projects.

### ISSUE THREAD

**Issue by HackPoint** [PacktPublishing/Angular-Projects-Second-Edition#8]
Please add more information when and why you do this and that.

**Comment by HackPoint** [comment]
> Hello @HackPoint 👋 Is there any specific issue that I could help you with? Any problems with a specific chapter?

Yes, for example in chapter 4 it's not enough explanations on how to run it on MAC.
Not enough coverage on the tools and techniques, architecture discussions. Not enough of why to choose this or that tool.

Sorry of being annoying. But that's what I'm missing from what I've tried to understand.

**Comment by HackPoint** [comment]
@bampakoa just tested your code example on my Mac and isn't running. Could you please verify why?
MacBook Pro (16-inch, 2019);2.4 GHz 8-Core Intel Core i9
Catalina: 10.15.7

**Comment by bampakoa** [comment]
>Sorry of being annoying. But that's what I'm missing from what I've tried to understand.

No problem @HackPoint I am really glad for your feedback 👍 This will help me improve the content. Thank you so much 🙏 

>@bampakoa just tested your code example on my Mac and isn't running. Could you please verify why?
MacBook Pro (16-inch, 2019);2.4 GHz 8-Core Intel Core i9
Catalina: 10.15.7

Can you please give more details? Which part is not running correctly? What error message do you get?
