### ISSUE TITLE
Having trouble with this line of code.

### ISSUE THREAD

**Issue by bl4keee** [PacktPublishing/Angular-Projects-Second-Edition#9]
Hi. I am running new Angular 13 and this line does not really work properly. 
I am getting a weird communicate that: Type 'Subscription' is missing the following properties from type 'Subscription' (on this.routeSub). Have you worked that out by any chance?

https://github.com/PacktPublishing/Angular-Projects-Second-Edition/blob/aa55d922633c97b9813e7f01a7075148c97a0312/Chapter02/src/app/articles/articles.component.ts#L18

**Comment by bampakoa** [comment]
Hello @bl4keee 👋 Could you please report the full error message that you get?

**Comment by bl4keee** [comment]
Hi. I am attaching two screenshots below.

![1](https://user-images.githubusercontent.com/50672367/164260907-30d77324-50d8-4b68-b52e-812c6a1d26ff.PNG)

![2](https://user-images.githubusercontent.com/50672367/164260929-b1ef3926-d397-47a8-a9be-b06af25aa0e3.PNG)

**Comment by bl4keee** [comment]
> Hi. I am attaching two screenshots below.
> 
> ![1](https://user-images.githubusercontent.com/50672367/164260907-30d77324-50d8-4b68-b52e-812c6a1d26ff.PNG)
> 
> ![2](https://user-images.githubusercontent.com/50672367/164260929-b1ef3926-d397-47a8-a9be-b06af25aa0e3.PNG)

**Comment by bl4keee** [comment]
> Hello @bl4keee 👋 Could you please report the full error message that you get?

Hi @bampakoa, I am attaching two screenshots below.

![1](https://user-images.githubusercontent.com/50672367/164261373-cd5fc554-d99a-4d66-88c8-2933ded524ed.PNG)

![2](https://user-images.githubusercontent.com/50672367/164261391-96f329fe-7857-4330-88ea-5610e9edd49d.PNG)

**Comment by bampakoa** [comment]
Thank you so much! I cannot say much from the error message. Could you please also share your `package.json` file and your `articles.component.ts` file?

**Comment by bl4keee** [comment]
I guess that is not a big of a deal for sure, just because the code goes through all of the required commands and the articles are displayed in the end. I was just wondering how to get rid of this piece in terms of persisting clean code practice. Maybe it has to do with the new version of Angular 13 and scully not keeping up yet. 

`package.json`

![image](https://user-images.githubusercontent.com/50672367/164263159-44b6df1b-e02d-4328-b8c5-9ea1ad2be8a7.png)

`articles.component.ts`

![image](https://user-images.githubusercontent.com/50672367/164263272-c68a6224-eafa-451b-8bfa-ebcf4f819311.png)

**Comment by bampakoa** [comment]
@bl4keee of course it is a big deal. You got a book that you want to work as expected. I will do my best to help you 😃 

Could you please try to upgrade `rxjs` to **7.5.0**  and `@scullyio/init` to **2.1.32** ?

**Comment by bl4keee** [comment]
Having updated angular to 13.3.3 and scully to 2.1.32 helped to resolve my problem. Thanks!
